{"failedTests":[{"testName":"benchmark/test-benchmark-crypto","timestamp":1761474983994,"status":"FAILED","jobName":"node-test-binary-windows-native-suites","config":"node-test-binary-windows-native-suites Â» win2019-vs2019-COMPILED_BY-vs2022 #30184","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2019-vs2019-COMPILED_BY-vs2022/30184/","buildNumber":30184,"builtOn":"test-rackspace-win2019_vs2019-x64-3","nodeVersion":"22.21.1","commitHash":"76b4cab8fc59e0f4721a3dd1b1762c4707e7df3b","callStack":[{"upstreamBuild":73721,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":83541,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":369,"upstreamProject":"node-daily-v22.x-staging","upstreamUrl":"job/node-daily-v22.x-staging/"}],"tap":{"ok":false,"name":"benchmark/test-benchmark-crypto","id":186,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"node:assert:150\n  throw new AssertionError(obj);\n  ^\n\nAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\n1 !== 0\n\n    at main (C:\\workspace\\node-test-binary-windows-native-suites\\node\\benchmark\\crypto\\timingSafeEqual.js:21:10)\n    at C:\\workspace\\node-test-binary-windows-native-suites\\node\\benchmark\\common.js:63:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {\n  generatedMessage: true,\n  code: 'ERR_ASSERTION',\n  actual: 1,\n  expected: 0,\n  operator: 'strictEqual',\n  diff: 'simple'\n}\n\nNode.js v22.21.1-pre\nnode:internal/process/promises:392\n      new UnhandledPromiseRejection(reason);\n      ^\n\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"1\".\n    at throwUnhandledRejectionsMode (node:internal/process/promises:392:7)\n    at processPromiseRejections (node:internal/process/promises:475:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:106:32) {\n  code: 'ERR_UNHANDLED_REJECTION'\n}\n\nNode.js v22.21.1-pre\nnode:assert:150\n  throw new AssertionError(obj);\n  ^\n\nAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\n1 !== 0\n\n    at ChildProcess.<anonymous> (C:\\workspace\\node-test-binary-windows-native-suites\\node\\test\\common\\benchmark.js:28:12)\n    at ChildProcess.emit (node:events:519:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {\n  generatedMessage: true,\n  code: 'ERR_ASSERTION',\n  actual: 1,\n  expected: 0,\n  operator: 'strictEqual',\n  diff: 'simple'\n}\n\nNode.js v22.21.1-pre"},"time":6916.092,"fullname":"benchmark/test-benchmark-crypto","closingTestPoint":false}}]}