{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725232723943,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #29835","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/29835/","buildNumber":29835,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"23.0.0","commitHash":"f6ba6112f62ed51f893f9e557548aba6e7bbcd2d","callStack":[{"upstreamBuild":65393,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73797,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61801,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53550"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":108,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4706.0211ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (4275.5382ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4071.2673ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4597.9208ms)\n  ✖ async-hooks\\test-async-local-storage-enable-disable.js (4699.7854ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 4)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4409.5025ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5093.0789ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4803.2569ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (4748.2893ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (4428.3762ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (4982.5116ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4190.8374ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (4695.4074ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4204.5166ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4932.6995ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (4396.558ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (4991.3752ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4308.8187ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4379.3384ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4598.5751ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4289.7434ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (4845.692ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4366.6684ms)\n▶ AsyncContextFrame (5695.8594ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5711.091\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-enable-disable.js (4699.7854ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 4)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":6244.041,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}