{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725527299090,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win10-COMPILED_BY-vs2022 #29969","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/29969/","buildNumber":29969,"builtOn":"test-azure_msft-win10_vs2019-x64-2","nodeVersion":"23.0.0","commitHash":"3ffcebd7a724cfb8d4198312eb85c31b62c22a0a","callStack":[{"upstreamBuild":65539,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73973,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61969,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54776"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":89,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4534.8255ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (4526.8308ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4943.5738ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4406.4397ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (4485.8427ms)\n  ✖ async-hooks\\test-async-local-storage-enter-with.js (4842.2574ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:898:9)\n        at async Promise.all (index 5)\n        at async Suite.run (node:internal/test_runner/test:1278:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-errors.js (4834.7013ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5207.3256ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5335.7198ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5273.9576ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5241.3382ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5188.227ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (4662.0644ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4875.8827ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (5273.2947ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5154.9909ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (4986.1746ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4908.5341ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4758.2971ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4707.7125ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4961.971ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5179.9815ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5069.4201ms)\n▶ AsyncContextFrame (5390.4791ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5397.9961\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-enter-with.js (4842.2574ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:898:9)\n      at async Promise.all (index 5)\n      at async Suite.run (node:internal/test_runner/test:1278:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":5818.015,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-worker-arraybuffer-zerofill","timestamp":1725527299090,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 0,win2022-COMPILED_BY-vs2022 #29969","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/29969/","buildNumber":29969,"builtOn":"test-rackspace-win2022_vs2022-x64-4","nodeVersion":"23.0.0","commitHash":"3ffcebd7a724cfb8d4198312eb85c31b62c22a0a","callStack":[{"upstreamBuild":65539,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73973,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61969,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54776"}],"tap":{"ok":false,"name":"parallel/test-worker-arraybuffer-zerofill","id":956,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":120234.959,"fullname":"parallel/test-worker-arraybuffer-zerofill","closingTestPoint":false}}]}