{"failedTests":[{"testName":"parallel/test-runner-watch-mode","timestamp":1725550637098,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win10-COMPILED_BY-vs2022 #29984","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022/29984/","buildNumber":29984,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"4cd82f1a179994f9ed5cb2274bee651d45b3b94c","callStack":[{"upstreamBuild":65559,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73995,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61989,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54651"}],"tap":{"ok":false,"name":"parallel/test-runner-watch-mode","id":921,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout\n▶ test runner watch mode\n  ✔ should run tests repeatedly (4684.1736ms)\n  ✖ should run tests with dependency repeatedly (6043.9802ms)\n    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:\n    \n    '✔ test has ran (10.5884ms)\\n' +\n      '✖ c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\.tmp.687\\\\test.js (1049.986ms)\\n' +\n      \"  'test failed'\\n\" +\n      '\\n' +\n      '✔ test has ran (10.3301ms)\\n' +\n      '✖ c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\.tmp.687\\\\test.js (983.2606ms)\\n' +\n      \"  'test failed'\\n\" +\n      '\\n' +\n      '✔ test has ran (10.767ms)\\n' +\n      'ℹ tests 5\\n' +\n      'ℹ suites 0\\n' +\n      'ℹ pass 3\\n' +\n      'ℹ fail 2\\n' +\n      'ℹ cancelled 0\\n' +\n      'ℹ skipped 0\\n' +\n      'ℹ todo 0\\n' +\n      'ℹ duration_ms 1253.3922\\n'\n    \n        at testUpdate (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode.mjs:80:14)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async testWatch (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode.mjs:161:26)\n        at async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode.mjs:174:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:584:7) {\n      generatedMessage: true,\n      code: 'ERR_ASSERTION',\n      actual: \"✔ test has ran (10.5884ms)\\n✖ c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\.tmp.687\\\\test.js (1049.986ms)\\n  'test failed'\\n\\n✔ test has ran (10.3301ms)\\n✖ c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\.tmp.687\\\\test.js (983.2606ms)\\n  'test failed'\\n\\n✔ test has ran (10.767ms)\\nℹ tests 5\\n...\",\n      expected: /tests 1/,\n      operator: 'match'\n    }\n\n  ✔ should run tests with ESM dependency (4315.6094ms)"},"time":121845.112,"fullname":"parallel/test-runner-watch-mode","closingTestPoint":false}},{"testName":"parallel/test-async-context-frame","timestamp":1725550637098,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #29984","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/29984/","buildNumber":29984,"builtOn":"test-rackspace-win2022_vs2022-x64-5","nodeVersion":"23.0.0","commitHash":"4cd82f1a179994f9ed5cb2274bee651d45b3b94c","callStack":[{"upstreamBuild":65559,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":73995,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":61989,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54651"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":109,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4925.2319ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (4759.3898ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (5366.1371ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4728.12ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (4929.3337ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (5397.4645ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5609.6282ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5077.3378ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5082.4541ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5087.1504ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5159.0878ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5159.8501ms)\n  ✖ async-hooks\\test-async-local-storage-no-mix-contexts.js (6091.3674ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-no-mix-contexts.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 12)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-promises.js (4970.4448ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4970.6421ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (4904.2589ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5138.1866ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5074.342ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (5190.5493ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5521.3155ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5590.0834ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5542.8884ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4988.1933ms)\n▶ AsyncContextFrame (6370.7674ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 6386.6501\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-no-mix-contexts.js (6091.3674ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-no-mix-contexts.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 12)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":6944.222,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}