{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725597081555,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30010","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30010/","buildNumber":30010,"builtOn":"test-rackspace-win2022_vs2022-x64-6","nodeVersion":"23.0.0","commitHash":"3d83fe5a8fb3897cd1c5dbad4cc4bf9f3986b0fa","callStack":[{"upstreamBuild":65592,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74039,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62033,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54643"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":109,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5471.0578ms)\n  ✖ async-hooks\\test-async-local-storage-async-await.js (5569.0356ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 1)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (5093.3213ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4882.1505ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5164.8992ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (5414.3673ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (4514.1856ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4741.7611ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (4979.9653ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5425.3189ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5315.9796ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4290.5202ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (6025.5045ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4782.4363ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (5405.8003ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5211.6124ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5145.5503ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5068.3821ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (5363.2193ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5200.3089ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5808.6601ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5706.9365ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5645.3382ms)\n▶ AsyncContextFrame (6931.0264ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 6946.4756\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-async-await.js (5569.0356ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 1)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":7449.088,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-async-context-frame","timestamp":1725597081555,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30010","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30010/","buildNumber":30010,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"23.0.0","commitHash":"3d83fe5a8fb3897cd1c5dbad4cc4bf9f3986b0fa","callStack":[{"upstreamBuild":65592,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74039,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62033,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54643"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":107,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5216.9361ms)\n  ✖ async-hooks\\test-async-local-storage-async-await.js (5098.2066ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 1)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (5327.1987ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4170.5104ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5064.261ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4941.2265ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (4868.077ms)\n  ✖ async-hooks\\test-async-local-storage-gcable.js (4629.2005ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 7)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5441.7248ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (4783.4155ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5051.5096ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4388.2678ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (4983.4884ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4599.9331ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4623.9184ms)\n  ✖ async-hooks\\test-async-local-storage-thenable.js (4933.0727ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-thenable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 15)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5085.5485ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4758.6984ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4981.0185ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4721.6483ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4943.4314ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (4965.7412ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4788.3999ms)\n▶ AsyncContextFrame (5553.7656ms)\nℹ tests 23\nℹ suites 1\nℹ pass 20\nℹ fail 3\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5568.9879\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-async-await.js (5098.2066ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 1)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-gcable.js (4629.2005ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 7)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-thenable.js (4933.0727ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-thenable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 15)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":6187.031,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-runner-run-watch","timestamp":1725597081555,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win10-COMPILED_BY-vs2022 #30010","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/30010/","buildNumber":30010,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"3d83fe5a8fb3897cd1c5dbad4cc4bf9f3986b0fa","callStack":[{"upstreamBuild":65592,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74039,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62033,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54643"}],"tap":{"ok":false,"name":"parallel/test-runner-run-watch","id":899,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":121961.187,"fullname":"parallel/test-runner-run-watch","closingTestPoint":false}}]}