{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725656943387,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win10-COMPILED_BY-vs2022 #30040","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/30040/","buildNumber":30040,"builtOn":"test-azure_msft-win10_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"104de8ab88befd5340a50f10d619e0c7374042f8","callStack":[{"upstreamBuild":65626,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74087,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62076,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54739"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":93,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4538.3846ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (5177.0759ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4674.3774ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4713.6857ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (4509.6745ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4273.1297ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5250.9148ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4324.4622ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5332.4575ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5078.1661ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5245.1611ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4979.3244ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5346.2219ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4919.2991ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4631.4696ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (4904.3187ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5091.7838ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5055.6109ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (5085.4979ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4501.6424ms)\n  ✖ parallel\\test-async-local-storage-exit-does-not-leak.js (5003.9962ms)\n    AssertionError [ERR_ASSERTION]: Test parallel\\test-async-local-storage-exit-does-not-leak.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 20)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5266.6789ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4976.1375ms)\n▶ AsyncContextFrame (5557.7154ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5566.4092\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ parallel\\test-async-local-storage-exit-does-not-leak.js (5003.9962ms)\n  AssertionError [ERR_ASSERTION]: Test parallel\\test-async-local-storage-exit-does-not-leak.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 20)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":5957.035,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-runner-watch-mode-complex","timestamp":1725656943387,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 0,win10-COMPILED_BY-vs2022 #30040","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/30040/","buildNumber":30040,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"104de8ab88befd5340a50f10d619e0c7374042f8","callStack":[{"upstreamBuild":65626,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74087,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62076,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54739"}],"tap":{"ok":false,"name":"parallel/test-runner-watch-mode-complex","id":695,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ test runner watch mode with more complex setup\n  ✖ should run tests when a dependency changed after a watched test file being deleted (6998.6259ms)\n    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 2/. Input:\n    \n    '✔ second test has ran (18.938ms)\\n' +\n      '✖ test-2.mjs (1125.5486ms)\\n' +\n      \"  'test failed'\\n\" +\n      '\\n' +\n      '✔ first test has ran (23.3708ms)\\n' +\n      '✔ first test has ran (33.7264ms)\\n' +\n      '✖ test.js (1038.7975ms)\\n' +\n      \"  'test failed'\\n\" +\n      '\\n' +\n      '✔ second test has ran (10.4566ms)\\n' +\n      '✔ first test has ran (10.7606ms)\\n' +\n      'ℹ tests 7\\n' +\n      'ℹ suites 0\\n' +\n      'ℹ pass 5\\n' +\n      'ℹ fail 2\\n' +\n      'ℹ cancelled 0\\n' +\n      'ℹ skipped 0\\n' +\n      'ℹ todo 0\\n' +\n      'ℹ duration_ms 1834.9256\\n'\n    \n        at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode-complex.mjs:99:12)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 0)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: true,\n      code: 'ERR_ASSERTION',\n      actual: \"✔ second test has ran (18.938ms)\\n✖ test-2.mjs (1125.5486ms)\\n  'test failed'\\n\\n✔ first test has ran (23.3708ms)\\n✔ first test has ran (33.7264ms)\\n✖ test.js (1038.7975ms)\\n  'test failed'\\n\\n✔ second test has ran (10.4566ms)\\n...\",\n      expected: /tests 2/,\n      operator: 'match'\n    }\n\n▶ test runner watch mode with more complex setup (7029.1453ms)\nℹ tests 1\nℹ suites 1\nℹ pass 0\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 7172.9018\n\n✖ failing tests:\n\ntest at test\\parallel\\test-runner-watch-mode-complex.mjs:53:3\n✖ should run tests when a dependency changed after a watched test file being deleted (6998.6259ms)\n  AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 2/. Input:\n  \n  '✔ second test has ran (18.938ms)\\n' +\n    '✖ test-2.mjs (1125.5486ms)\\n' +\n    \"  'test failed'\\n\" +\n    '\\n' +\n    '✔ first test has ran (23.3708ms)\\n' +\n    '✔ first test has ran (33.7264ms)\\n' +\n    '✖ test.js (1038.7975ms)\\n' +\n    \"  'test failed'\\n\" +\n    '\\n' +\n    '✔ second test has ran (10.4566ms)\\n' +\n    '✔ first test has ran (10.7606ms)\\n' +\n    'ℹ tests 7\\n' +\n    'ℹ suites 0\\n' +\n    'ℹ pass 5\\n' +\n    'ℹ fail 2\\n' +\n    'ℹ cancelled 0\\n' +\n    'ℹ skipped 0\\n' +\n    'ℹ todo 0\\n' +\n    'ℹ duration_ms 1834.9256\\n'\n  \n      at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-watch-mode-complex.mjs:99:12)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 0)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: true,\n    code: 'ERR_ASSERTION',\n    actual: \"✔ second test has ran (18.938ms)\\n✖ test-2.mjs (1125.5486ms)\\n  'test failed'\\n\\n✔ first test has ran (23.3708ms)\\n✔ first test has ran (33.7264ms)\\n✖ test.js (1038.7975ms)\\n  'test failed'\\n\\n✔ second test has ran (10.4566ms)\\n...\",\n    expected: /tests 2/,\n    operator: 'match'\n  }"},"time":50220.157,"fullname":"parallel/test-runner-watch-mode-complex","closingTestPoint":false}}]}