{"failedTests":[{"testName":"parallel/test-runner-run-watch","timestamp":1725789981114,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win10-COMPILED_BY-vs2022 #30101","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/30101/","buildNumber":30101,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"55c83d084db360b591efde304002504d9f586f57","callStack":[{"upstreamBuild":65697,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74171,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62157,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54642"}],"tap":{"ok":false,"name":"parallel/test-runner-run-watch","id":898,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout\n▶ test runner watch mode\n  ✖ should run tests repeatedly (5349.7731ms)\n    AssertionError [ERR_ASSERTION]: The input did not match the regular expression /tests 1/. Input:\n    \n    '# Subtest: test.js\\n' +\n      'not ok 2 - test.js\\n' +\n      '  ---\\n' +\n      '  duration_ms: 1028.6406\\n' +\n      \"  location: 'c:\\\\\\\\workspace\\\\\\\\node-test-binary-windows-js-suites\\\\\\\\node\\\\\\\\test\\\\\\\\.tmp.685\\\\\\\\test.js:1:1'\\n\" +\n      \"  failureType: 'testCodeFailure'\\n\" +\n      '  exitCode: ~\\n' +\n      \"  signal: 'SIGTERM'\\n\" +\n      \"  error: 'test failed'\\n\" +\n      \"  code: 'ERR_TEST_FAILURE'\\n\" +\n      '  ...\\n' +\n      '# Subtest: test has ran\\n' +\n      'ok 2 - test has ran\\n' +\n      '  ---\\n' +\n      '  duration_ms: 18.3861\\n' +\n      '  ...\\n' +\n      '1..2\\n' +\n      '# tests 2\\n' +\n      '# suites 0\\n' +\n      '# pass 1\\n' +\n      '# fail 1\\n' +\n      '# cancelled 0\\n' +\n      '# skipped 0\\n' +\n      '# todo 0\\n' +\n      '# duration_ms 1249.7181\\n'\n    \n        at testUpdate (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-run-watch.mjs:81:14)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async testWatch (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-run-watch.mjs:173:26)\n        at async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-runner-run-watch.mjs:183:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 0)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: true,\n      code: 'ERR_ASSERTION',\n      actual: \"# Subtest: test.js\\nnot ok 2 - test.js\\n  ---\\n  duration_ms: 1028.6406\\n  location: 'c:\\\\\\\\workspace\\\\\\\\node-test-binary-windows-js-suites\\\\\\\\node\\\\\\\\test\\\\\\\\.tmp.685\\\\\\\\test.js:1:1'\\n  failureType: 'testCodeFailure'\\n  exitCode: ~\\n  signal: 'SIGTERM'\\n  error: 'test failed'\\n  code: 'ERR_TEST_FAILURE'\\n...\",\n      expected: /tests 1/,\n      operator: 'match'\n    }"},"time":122035.045,"fullname":"parallel/test-runner-run-watch","closingTestPoint":false}},{"testName":"parallel/test-async-context-frame","timestamp":1725789981114,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30101","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30101/","buildNumber":30101,"builtOn":"test-rackspace-win2022_vs2022-x64-5","nodeVersion":"23.0.0","commitHash":"55c83d084db360b591efde304002504d9f586f57","callStack":[{"upstreamBuild":65697,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74171,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62157,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54642"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":109,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4960.2681ms)\n  ✖ async-hooks\\test-async-local-storage-async-await.js (4392.6215ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 1)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4390.7126ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (4660.9163ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (3976.3551ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4345.9441ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (4733.3187ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4420.8469ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (4545.7296ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (3902.6907ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (4352.7754ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4263.3012ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (4792.0285ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (4730.9152ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (4751.1996ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (3995.1944ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (4860.3574ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4690.001ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4949.4349ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4191.8074ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4782.2804ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (4406.6473ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4122.9785ms)\n▶ AsyncContextFrame (5376.9667ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5398.4535\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-async-await.js (4392.6215ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 1)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":5857.21,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}