{"failedTests":[{"testName":"parallel/test-runner-run-watch","timestamp":1725923378505,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 3,win10-COMPILED_BY-vs2022 #30138","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/30138/","buildNumber":30138,"builtOn":"test-azure_msft-win10_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"0975d884105cc8792cb772952bd3fe61eb5b6484","callStack":[{"upstreamBuild":65750,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74239,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62217,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54834"}],"tap":{"ok":false,"name":"parallel/test-runner-run-watch","id":896,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":121845.766,"fullname":"parallel/test-runner-run-watch","closingTestPoint":false}},{"testName":"parallel/test-async-context-frame","timestamp":1725923378505,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30138","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30138/","buildNumber":30138,"builtOn":"test-rackspace-win2022_vs2022-x64-2","nodeVersion":"23.0.0","commitHash":"0975d884105cc8792cb772952bd3fe61eb5b6484","callStack":[{"upstreamBuild":65750,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74239,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62217,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54834"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":113,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5506.2749ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (5304.3064ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4833.4473ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (5763.0217ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (4837.2682ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (5412.9151ms)\n  ✖ async-hooks\\test-async-local-storage-errors.js (5031.8311ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-errors.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 6)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5329.5059ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5185.8457ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5626.2101ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (6027.9759ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5104.0481ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (6017.1682ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (5778.6159ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (6050.8277ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5387.2661ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (6149.971ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5868.9478ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4514.7803ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5078.3191ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5183.9208ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (5292.2095ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5640.673ms)\n▶ AsyncContextFrame (6833.9147ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 6851.2813\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-errors.js (5031.8311ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-errors.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 6)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":7316.097,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}