{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725921773366,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30136","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30136/","buildNumber":30136,"builtOn":"test-rackspace-win2022_vs2022-x64-2","nodeVersion":"23.0.0","commitHash":"ba1665027a1258824ac33abfc8c382c7ab398311","callStack":[{"upstreamBuild":65742,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74226,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62205,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54552"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":115,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5050.7864ms)\n  ✖ async-hooks\\test-async-local-storage-async-await.js (5830.8871ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 1)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4837.7626ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (5461.8791ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5466.1025ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4804.3355ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5401.581ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5181.4378ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5983.7332ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5154.9931ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5340.5829ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5091.3472ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5385.6533ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (5063.5024ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (5581.511ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5728.4464ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (6181.4882ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5052.354ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4791.8097ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5306.5387ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5389.2879ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (6673.4611ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (5547.9271ms)\n▶ AsyncContextFrame (7003.172ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 7019.1475\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-async-await.js (5830.8871ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 1)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":7559.093,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-worker-arraybuffer-zerofill","timestamp":1725921773366,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win2019-COMPILED_BY-vs2022 #30136","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/30136/","buildNumber":30136,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"23.0.0","commitHash":"ba1665027a1258824ac33abfc8c382c7ab398311","callStack":[{"upstreamBuild":65742,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74226,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62205,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54552"}],"tap":{"ok":false,"name":"parallel/test-worker-arraybuffer-zerofill","id":1000,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":120139.386,"fullname":"parallel/test-worker-arraybuffer-zerofill","closingTestPoint":false}}]}