{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727187012569,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win10-COMPILED_BY-vs2022 #30502","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022/30502/","buildNumber":30502,"builtOn":"test-azure_msft-win10_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"ff25b9969b5753dcf32b6b56a613459acf203365","callStack":[{"upstreamBuild":66195,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74770,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62728,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55089"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":279,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (853.4953ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (938.2226ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1232.5978ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (982.8819ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1103.8322ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (943.9858ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1146.9201ms)\n  ✖ async-hooks\\test-async-local-storage-gcable.js (1041.9815ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:931:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (810.4311ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1363.3713ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1160.942ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1018.9197ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1349.8083ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (813.0955ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (726.2629ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (744.3672ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1066.1226ms)\n  ✔ parallel\\test-async-local-storage-bind.js (731.155ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (748.2713ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (775.9689ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (963.7878ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (925.8335ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (729.8935ms)\n✖ AsyncContextFrame (22179.9659ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 22186.6226\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-gcable.js (1041.9815ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:931:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":22519.127,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}