{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727636107227,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30600","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30600/","buildNumber":30600,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"e0a22b50af2f39cd91d0ec2b19e68aa0c9e2e684","callStack":[{"upstreamBuild":66297,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74904,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62847,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55125"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":442,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1553.7095ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (2115.7215ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1895.7632ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1833.9069ms)\n  ✖ async-hooks\\test-async-local-storage-enable-disable.js (1453.8723ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1689.2103ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1481.3653ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1574.5182ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1804.8292ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1633.1286ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1553.9222ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1692.001ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (2237.25ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1828.3904ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1563.5677ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1394.7777ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1519.8229ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1228.4796ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1273.1885ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1270.7594ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1329.8113ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1566.6431ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1324.8834ms)\n✖ AsyncContextFrame (36837.4817ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 36855.3161\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enable-disable.js (1453.8723ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":37395.911,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}