{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727819819842,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30640","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30640/","buildNumber":30640,"builtOn":"test-rackspace-win2019_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"4528fd6ac0403fbde285541fed4123b45fffab96","callStack":[{"upstreamBuild":66337,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74948,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62883,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55071"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":431,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✖ async-hooks\\test-async-local-storage-args.js (1634.143ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-args.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Promise.all (index 0)\n        at async Suite.run (node:internal/test_runner/test:1320:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:296:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-await.js (2203.9593ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (2019.7008ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (2117.5781ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1674.1232ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1732.4108ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1624.6761ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (2083.0555ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1838.6938ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1618.8137ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1487.5245ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1425.8432ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1913.8746ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1418.9706ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1483.4981ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1293.3793ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1561.0356ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1415.4852ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1278.5652ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1210.4375ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1266.3659ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1621.1866ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1236.3565ms)\n✖ AsyncContextFrame (37175.0381ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 37189.8054\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-args.js (1634.143ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-args.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Promise.all (index 0)\n      at async Suite.run (node:internal/test_runner/test:1320:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:296:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":37648.279,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}