{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1728907794874,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win2019-COMPILED_BY-vs2022 #30832","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/30832/","buildNumber":30832,"builtOn":"test-rackspace-win2019_vs2019-x64-1","nodeVersion":"23.0.0","commitHash":"deb6214ebcf3da65ec2c1d9e2bec29f8964ae94e","callStack":[{"upstreamBuild":66531,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":75197,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":63094,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55266"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":437,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1824.2737ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1788.9606ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1862.1018ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (3044.4723ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1727.0539ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (2315.3973ms)\n  ✖ async-hooks\\test-async-local-storage-errors.js (2522.3536ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-errors.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1989.1974ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (2128.9379ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1774.3281ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1663.1658ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1456.4434ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1849.303ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1402.5287ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1306.7969ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1242.1619ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1524.1662ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1442.6331ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1293.5914ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1399.191ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1411.8211ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1753.4555ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1466.5299ms)\n✖ AsyncContextFrame (40208.4234ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 40227.6459\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-errors.js (2522.3536ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-errors.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":40748.045,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}