{"failedTests":[{"testName":"parallel/test-without-async-context-frame","timestamp":1732591694428,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 0,win2019-COMPILED_BY-vs2022 #31397","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022/31397/","buildNumber":31397,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"24.0.0","commitHash":"6cefd813ff32b09c4d9b61f36b529acaac3b2f7f","callStack":[{"upstreamBuild":67122,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":75992,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":63705,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55915"}],"tap":{"ok":false,"name":"parallel/test-without-async-context-frame","id":979,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ without AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1428.8627ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1189.3521ms)\n  ✖ async-hooks\\test-async-local-storage-async-functions.js (1525.6635ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-without-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:932:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1463.3602ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1161.7962ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1089.1817ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1134.8094ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1161.9481ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1163.9895ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1195.8368ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1119.4858ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1137.143ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1677.2026ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1210.4538ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1158.7304ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1109.4767ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1330.8067ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1105.5404ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1137.7622ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1109.2042ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1146.6333ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1396.2924ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1086.4902ms)\n✖ without AsyncContextFrame (28255.2446ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 28270.4415\n\n✖ failing tests:\n\ntest at test\\parallel\\test-without-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-async-functions.js (1525.6635ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-functions.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-without-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:932:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":28692.197,"fullname":"parallel/test-without-async-context-frame","closingTestPoint":false}}]}