{"failedTests":[{"testName":"parallel/test-without-async-context-frame","timestamp":1733947582438,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win2019-COMPILED_BY-vs2022 #31657","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/31657/","buildNumber":31657,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"24.0.0","commitHash":"e0435f088b7e84de4e16d45cc2711108b74d7804","callStack":[{"upstreamBuild":67393,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":76375,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":64011,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55985"}],"tap":{"ok":false,"name":"parallel/test-without-async-context-frame","id":977,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ without AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1595.1717ms)\n  ✖ async-hooks\\test-async-local-storage-async-await.js (1880.7856ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-without-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:932:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1336.4754ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1165.6164ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1110.8657ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1101.3797ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1075.5004ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1184.0936ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1149.5285ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1147.6012ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1084.8003ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1103.5944ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1523.2425ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1106.8126ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1154.5ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1092.3487ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1236.5856ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1099.842ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1135.0882ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1105.3242ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1072.7545ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1415.5114ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1214.1225ms)\n✖ without AsyncContextFrame (28107.168ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 28122.4489\n\n✖ failing tests:\n\ntest at test\\parallel\\test-without-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-async-await.js (1880.7856ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-async-await.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-without-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:932:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":28715.174,"fullname":"parallel/test-without-async-context-frame","closingTestPoint":false}}]}